require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CorrespondentsController do

  # This should return the minimal set of attributes required to create a valid
  # Correspondent. As you add validations to Correspondent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CorrespondentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all correspondents as @correspondents" do
      correspondent = Correspondent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:correspondents).should eq([correspondent])
    end
  end

  describe "GET show" do
    it "assigns the requested correspondent as @correspondent" do
      correspondent = Correspondent.create! valid_attributes
      get :show, {:id => correspondent.to_param}, valid_session
      assigns(:correspondent).should eq(correspondent)
    end
  end

  describe "GET new" do
    it "assigns a new correspondent as @correspondent" do
      get :new, {}, valid_session
      assigns(:correspondent).should be_a_new(Correspondent)
    end
  end

  describe "GET edit" do
    it "assigns the requested correspondent as @correspondent" do
      correspondent = Correspondent.create! valid_attributes
      get :edit, {:id => correspondent.to_param}, valid_session
      assigns(:correspondent).should eq(correspondent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Correspondent" do
        expect {
          post :create, {:correspondent => valid_attributes}, valid_session
        }.to change(Correspondent, :count).by(1)
      end

      it "assigns a newly created correspondent as @correspondent" do
        post :create, {:correspondent => valid_attributes}, valid_session
        assigns(:correspondent).should be_a(Correspondent)
        assigns(:correspondent).should be_persisted
      end

      it "redirects to the created correspondent" do
        post :create, {:correspondent => valid_attributes}, valid_session
        response.should redirect_to(Correspondent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved correspondent as @correspondent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Correspondent.any_instance.stub(:save).and_return(false)
        post :create, {:correspondent => {}}, valid_session
        assigns(:correspondent).should be_a_new(Correspondent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Correspondent.any_instance.stub(:save).and_return(false)
        post :create, {:correspondent => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested correspondent" do
        correspondent = Correspondent.create! valid_attributes
        # Assuming there are no other correspondents in the database, this
        # specifies that the Correspondent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Correspondent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => correspondent.to_param, :correspondent => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested correspondent as @correspondent" do
        correspondent = Correspondent.create! valid_attributes
        put :update, {:id => correspondent.to_param, :correspondent => valid_attributes}, valid_session
        assigns(:correspondent).should eq(correspondent)
      end

      it "redirects to the correspondent" do
        correspondent = Correspondent.create! valid_attributes
        put :update, {:id => correspondent.to_param, :correspondent => valid_attributes}, valid_session
        response.should redirect_to(correspondent)
      end
    end

    describe "with invalid params" do
      it "assigns the correspondent as @correspondent" do
        correspondent = Correspondent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Correspondent.any_instance.stub(:save).and_return(false)
        put :update, {:id => correspondent.to_param, :correspondent => {}}, valid_session
        assigns(:correspondent).should eq(correspondent)
      end

      it "re-renders the 'edit' template" do
        correspondent = Correspondent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Correspondent.any_instance.stub(:save).and_return(false)
        put :update, {:id => correspondent.to_param, :correspondent => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested correspondent" do
      correspondent = Correspondent.create! valid_attributes
      expect {
        delete :destroy, {:id => correspondent.to_param}, valid_session
      }.to change(Correspondent, :count).by(-1)
    end

    it "redirects to the correspondents list" do
      correspondent = Correspondent.create! valid_attributes
      delete :destroy, {:id => correspondent.to_param}, valid_session
      response.should redirect_to(correspondents_url)
    end
  end

end
