require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KasesController do

  # This should return the minimal set of attributes required to create a valid
  # Kase. As you add validations to Kase, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KasesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all kases as @kases" do
      kase = Kase.create! valid_attributes
      get :index, {}, valid_session
      assigns(:kases).should eq([kase])
    end
  end

  describe "GET show" do
    it "assigns the requested kase as @kase" do
      kase = Kase.create! valid_attributes
      get :show, {:id => kase.to_param}, valid_session
      assigns(:kase).should eq(kase)
    end
  end

  describe "GET new" do
    it "assigns a new kase as @kase" do
      get :new, {}, valid_session
      assigns(:kase).should be_a_new(Kase)
    end
  end

  describe "GET edit" do
    it "assigns the requested kase as @kase" do
      kase = Kase.create! valid_attributes
      get :edit, {:id => kase.to_param}, valid_session
      assigns(:kase).should eq(kase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Kase" do
        expect {
          post :create, {:kase => valid_attributes}, valid_session
        }.to change(Kase, :count).by(1)
      end

      it "assigns a newly created kase as @kase" do
        post :create, {:kase => valid_attributes}, valid_session
        assigns(:kase).should be_a(Kase)
        assigns(:kase).should be_persisted
      end

      it "redirects to the created kase" do
        post :create, {:kase => valid_attributes}, valid_session
        response.should redirect_to(Kase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kase as @kase" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kase.any_instance.stub(:save).and_return(false)
        post :create, {:kase => {}}, valid_session
        assigns(:kase).should be_a_new(Kase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kase.any_instance.stub(:save).and_return(false)
        post :create, {:kase => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kase" do
        kase = Kase.create! valid_attributes
        # Assuming there are no other kases in the database, this
        # specifies that the Kase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Kase.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => kase.to_param, :kase => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested kase as @kase" do
        kase = Kase.create! valid_attributes
        put :update, {:id => kase.to_param, :kase => valid_attributes}, valid_session
        assigns(:kase).should eq(kase)
      end

      it "redirects to the kase" do
        kase = Kase.create! valid_attributes
        put :update, {:id => kase.to_param, :kase => valid_attributes}, valid_session
        response.should redirect_to(kase)
      end
    end

    describe "with invalid params" do
      it "assigns the kase as @kase" do
        kase = Kase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kase.any_instance.stub(:save).and_return(false)
        put :update, {:id => kase.to_param, :kase => {}}, valid_session
        assigns(:kase).should eq(kase)
      end

      it "re-renders the 'edit' template" do
        kase = Kase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kase.any_instance.stub(:save).and_return(false)
        put :update, {:id => kase.to_param, :kase => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kase" do
      kase = Kase.create! valid_attributes
      expect {
        delete :destroy, {:id => kase.to_param}, valid_session
      }.to change(Kase, :count).by(-1)
    end

    it "redirects to the kases list" do
      kase = Kase.create! valid_attributes
      delete :destroy, {:id => kase.to_param}, valid_session
      response.should redirect_to(kases_url)
    end
  end

end
